sudo: required

language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - "6"

services:
  - docker


before_install:
  # Pull container.
  - 'docker pull webdevops/ansible:alpine-3'

script:
  - npm test
  - docker run -t   webdevops/ansible:alpine-3 ansible --help


deploy:
  provider: script
  script:
    - docker run -t   webdevops/ansible:alpine-3 ansible --help
  on:
    branch: testTravis


# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
#notifications:
#  irc: "irc.freenode.org#travis"
